### ISSUE TITLE
Archive this site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/iheartopendata.org#40]
Let's take this site down and redirect it. I've migrated the content to a campaign on the foundation site, but the petition still needs to work there. Once the CRM petitions are working, let's hook the petition up to one and take it down.

@ScottDowne Can you find the shareprogress links we need to paste into wagtail for https://share.mozilla.org/352/179206 ?

**Comment by ScottDowne** [comment]
do we need to hunt down the previous signatures and migrate them or do something else with them?

**Comment by alanmoo** [comment]
Give them to @stephaniemcv?

**Comment by stephaniemcv** [comment]
Yup, give 'em to me.

**Comment by alanmoo** [comment]
@stephaniemcv, can you also create a campaign for this since I think that's now working? It'll probably not get any hits, but I'd rather unify us on one petition platform before figuring out how to "close" petitions.

**Comment by stephaniemcv** [comment]
This appears to be done, as I see a CampaignID in the snippet. I'm going to give credit to the amazing @desiree-mofo
